// Hover glossary for the animation lessons. Keys are lowercase French tokens.
window.SCENE_GLOSS = {
  words: {
    "a": "دارد",
    "à": "به",
    "abonne": "مشترک می‌شود",
    "abonnement": "اشتراک",
    "absent": "غایب",
    "accepté": "پذیرفته",
    "accès": "دسترسی",
    "accessible": "در دسترس",
    "accident": "تصادف",
    "accompagne": "همراهی می‌کند",
    "accueil": "پذیرش",
    "accueillir": "پذیرایی کردن",
    "accusé": "رسید",
    "acheté": "خریده",
    "achète": "می‌خرد",
    "achètes": "می‌خری",
    "achetons": "می‌خریم",
    "acide": "ترش",
    "acte": "سند",
    "acteur": "بازیگر",
    "activer": "فعال کردن",
    "activités": "فعالیت‌ها",
    "actualité": "اخبار",
    "adhère": "عضو می‌شود",
    "adhérent": "عضو",
    "adhésion": "عضویت",
    "adore": "خیلی دوست دارد",
    "adorent": "خیلی دوست دارند",
    "adresse": "آدرس",
    "aéroport": "فرودگاه",
    "affaire": "موضوع؛ کار",
    "âge": "سن",
    "âgé": "مسن",
    "âgée": "مسن",
    "âgées": "مسن",
    "agence": "آژانس",
    "agissons": "عمل می‌کنیم",
    "ai": "دارم",
    "aide": "کمک",
    "aider": "کمک کردن",
    "aime": "دوست دارد",
    "aiment": "دوست دارند",
    "air": "هوا",
    "ajoute": "اضافه می‌کند",
    "aliment": "خوراکی",
    "alimentaire": "غذایی",
    "allemand": "آلمانی",
    "aller": "رفتن",
    "alliances": "حلقه‌های ازدواج",
    "allons": "می‌رویم",
    "allume": "روشن می‌کند",
    "alpes": "آلپ",
    "alternance": "دورهٔ کار و تحصیل",
    "américain": "آمریکایی",
    "ami": "دوست",
    "amicale": "دوستانه",
    "amie": "دوست",
    "amis": "دوستان",
    "amitié": "دوستی",
    "amphithéâtre": "آمفی‌تئاتر",
    "amusant": "بامزه",
    "an": "سال",
    "analyses": "آزمایش‌ها",
    "ananas": "آناناس",
    "ancien": "قدیمی",
    "ancienne": "قدیمی",
    "anglais": "انگلیسی",
    "animale": "حیوانی",
    "animateur": "مجری",
    "animé": "زنده؛ شلوغ",
    "anniversaire": "تولد",
    "annonce": "آگهی",
    "ans": "سال",
    "antibiotiques": "آنتی‌بیوتیک",
    "août": "اوت",
    "apéritif": "پیش‌غذای نوشیدنی",
    "appartement": "آپارتمان",
    "appartiens": "تعلق دارم",
    "appeler": "تماس گرفتن",
    "appelle": "صدا می‌زند؛ نام دارد",
    "apprendre": "یاد گرفتن",
    "après": "بعد",
    "après-midi": "بعدازظهر",
    "après-vente": "خدمات پس از فروش",
    "arbre": "درخت",
    "arrêt": "ایستگاه",
    "arrive": "می‌رسد",
    "arrivé": "رسیده",
    "arrivée": "ورود",
    "arrivés": "رسیده‌اند",
    "art": "هنر",
    "article": "کالا؛ مقاله",
    "artifice": "آتش‌بازی",
    "artiste": "هنرمند",
    "as": "داری",
    "ascenseur": "آسانسور",
    "aspirine": "آسپرین",
    "assiette": "بشقاب",
    "assistance": "امداد",
    "assistante": "دستیار",
    "assister": "شرکت کردن",
    "association": "انجمن",
    "assurance": "بیمه",
    "atelier": "کارگاه",
    "attend": "منتظر است",
    "attendons": "منتظر هستیم",
    "attends": "منتظرم",
    "attention": "مراقب باش",
    "au": "به",
    "aubergine": "بادمجان",
    "aujourd'hui": "امروز",
    "aura": "خواهد داشت",
    "automatique": "خودکار",
    "automne": "پاییز",
    "automobiliste": "راننده",
    "autorisation": "مجوز",
    "autoroute": "آزادراه",
    "autre": "دیگر",
    "autres": "دیگران",
    "aux": "به",
    "avance": "از پیش",
    "avant": "قبل",
    "avec": "با",
    "avenue": "خیابان",
    "avion": "هواپیما",
    "avoir": "داشتن",
    "avons": "داریم",
    "avril": "آوریل",
    "bagages": "چمدان‌ها",
    "baguette": "باگت",
    "baignoire": "وان",
    "bail": "قرارداد اجاره",
    "bain": "حمام",
    "bains": "حمام",
    "bal": "مجلس رقص",
    "balade": "گردش",
    "balcon": "بالکن",
    "ballon": "بادکنک؛ توپ",
    "banane": "موز",
    "bancaire": "بانکی",
    "banlieue": "حومه",
    "banque": "بانک",
    "basket": "بسکتبال",
    "bateau": "قایق",
    "bâtiment": "ساختمان",
    "bavard": "پرحرف",
    "beau": "زیبا",
    "beaucoup": "خیلی",
    "bébé": "نوزاد",
    "bel": "زیبا",
    "belge": "بلژیکی",
    "belle": "زیبا",
    "bénévolat": "داوطلبی",
    "bénévole": "داوطلب",
    "bénévoles": "داوطلبان",
    "besoin": "نیاز",
    "beurre": "کره",
    "bibliothèque": "کتابخانه",
    "bien": "خوب",
    "bientôt": "به‌زودی",
    "bilan": "جمع‌بندی",
    "billet": "بلیت",
    "billets": "بلیت‌ها",
    "bio": "ارگانیک",
    "bise": "روبوسی",
    "blanche": "سفید",
    "blanches": "سفید",
    "blessée": "زخمی",
    "bleu": "آبی",
    "bleue": "آبی",
    "blog": "وبلاگ",
    "blond": "بور",
    "blonde": "بور",
    "bois": "می‌نوشم؛ بنوش",
    "boisson": "نوشیدنی",
    "boit": "می‌نوشد",
    "boîte": "جعبه",
    "bol": "کاسه",
    "bon": "خوب",
    "bonjour": "سلام",
    "bonne": "خوب",
    "bonnet": "کلاه بافتنی",
    "bord": "لب؛ کنار",
    "bouche": "دهان",
    "bouché": "گرفته",
    "bouchées": "لقمه‌ها",
    "boulevard": "بلوار",
    "bouteille": "بطری",
    "bouteilles": "بطری‌ها",
    "boutique": "فروشگاه",
    "box": "انباری",
    "bras": "بازو",
    "bravo": "آفرین",
    "brésilien": "برزیلی",
    "bronchite": "برونشیت",
    "bronzer": "آفتاب گرفتن",
    "brosse": "مسواک می‌زند",
    "bruit": "صدا",
    "brûlure": "سوختگی",
    "brun": "قهوه‌ای‌مو",
    "brune": "قهوه‌ای‌مو",
    "bruyante": "پرسر و صدا",
    "buffet": "بوفه",
    "bulles": "حباب‌ها",
    "bulletin": "کارنامه",
    "bureau": "دفتر",
    "bus": "اتوبوس",
    "but": "گل",
    "c.v": "رزومه",
    "c'": "این",
    "ça": "این",
    "cabinet": "مطب",
    "cadeau": "هدیه",
    "café": "قهوه",
    "cafés": "کافه‌ها",
    "cafétéria": "کافه تریا",
    "cahier": "دفتر",
    "caisse": "صندوق",
    "calme": "آرام",
    "camion": "کامیون",
    "campagne": "روستا",
    "campus": "پردیس دانشگاه",
    "canapé": "کاناپه",
    "candidat": "داوطلب شغل",
    "candidature": "درخواست شغل",
    "carafe": "پارچ",
    "caramel": "کارامل",
    "carnet": "دفترچه",
    "carotte": "هویج",
    "cartable": "کیف مدرسه",
    "carte": "کارت",
    "carton": "جعبهٔ مقوایی",
    "cartons": "جعبه‌ها",
    "cas": "مورد",
    "casse": "می‌شکند",
    "cassé": "شکسته",
    "cauchemar": "کابوس",
    "cause": "دلیل",
    "cave": "زیرزمین",
    "ce": "این",
    "ceinture": "کمربند",
    "célèbre": "مشهور",
    "célibataire": "مجرد",
    "centrale": "مرکزی",
    "centre": "مرکز",
    "centre-ville": "مرکز شهر",
    "centres": "مراکز",
    "cerises": "گیلاس‌ها",
    "ces": "این",
    "cet": "این",
    "cette": "این",
    "chambre": "اتاق",
    "chambres": "اتاق‌ها",
    "changement": "تغییر",
    "chant": "آواز",
    "chanteuse": "خواننده",
    "chaque": "هر",
    "chargé": "سنگین؛ مسئول",
    "charges": "هزینه‌ها",
    "charmant": "دل‌نشین",
    "chat": "گربه",
    "château": "قلعه",
    "chaud": "داغ",
    "chaude": "داغ",
    "chaudes": "داغ",
    "chauffage": "گرمایش",
    "chaussettes": "جوراب",
    "chaussures": "کفش",
    "chef": "مدیر",
    "chemise": "پیراهن",
    "chéquier": "دسته چک",
    "cher": "گران؛ عزیز",
    "cherche": "دنبال می‌گردد",
    "chercher": "دنبال گشتن",
    "cherchons": "دنبال می‌گردیم",
    "chez": "پیش",
    "chien": "سگ",
    "chinois": "چینی",
    "chips": "چیپس",
    "chocolat": "شکلات",
    "choisi": "انتخاب شده",
    "choisis": "انتخاب می‌کنم",
    "ciel": "آسمان",
    "cinéma": "سینما",
    "cinq": "پنج",
    "cinquante": "پنجاه",
    "circule": "رفت و آمد می‌کند",
    "circulent": "رفت و آمد می‌کنند",
    "citron": "لیمو",
    "civil": "مدنی",
    "classe": "کلاس",
    "classeur": "کلاسور",
    "clé": "کلید",
    "clés": "کلیدها",
    "client": "مشتری",
    "clignotant": "راهنما",
    "club": "باشگاه",
    "code": "رمز؛ کد",
    "coiffe": "مویش را مرتب می‌کند",
    "coin": "گوشه",
    "collaboration": "همکاری",
    "collecte": "جمع‌آوری",
    "collège": "راهنمایی",
    "collègue": "همکار",
    "collègues": "همکاران",
    "comédien": "بازیگر",
    "commande": "سفارش می‌دهد",
    "commander": "سفارش دادن",
    "comme": "مثل؛ به‌عنوان",
    "commence": "شروع می‌شود",
    "commerces": "مغازه‌ها",
    "commercial": "تجاری",
    "commun": "مشترک",
    "comparons": "مقایسه می‌کنیم",
    "compétence": "مهارت",
    "complété": "تکمیل کرده",
    "comprimé": "قرص",
    "comprises": "شامل",
    "compte": "حساب",
    "concentrer": "تمرکز کردن",
    "concert": "کنسرت",
    "concours": "مسابقه",
    "concrète": "عملی",
    "conducteur": "راننده",
    "conduire": "رانندگی کردن",
    "conduit": "رانندگی می‌کند",
    "conférence": "سخنرانی",
    "confirmé": "پیشرفته",
    "confortable": "راحت",
    "congés": "مرخصی",
    "connaissance": "آشنا",
    "connecte": "وصل می‌شود",
    "connexion": "اتصال",
    "connu": "شناخته‌شده",
    "conseil": "شورا؛ توصیه",
    "conseille": "پیشنهاد می‌کند",
    "consultation": "ویزیت",
    "consulte": "مراجعه می‌کند",
    "contrat": "قرارداد",
    "contre": "علیه؛ مقابل",
    "contrôle": "کنترل",
    "contrôleur": "بازرس",
    "convocation": "احضاریه",
    "copains": "رفیق‌ها",
    "coréen": "کره‌ای",
    "correspondance": "تعویض خط",
    "côté": "طرف",
    "cotisation": "حق عضویت",
    "coton": "پنبه",
    "couche": "می‌خوابد",
    "couloir": "راهرو",
    "coup": "ضربه",
    "coupe": "می‌بُرد",
    "couper": "بریدن",
    "couple": "زوج",
    "coupure": "قطع برق",
    "cour": "حیاط",
    "courant": "جاری",
    "courgette": "کدو سبز",
    "cours": "درس؛ می‌دوی",
    "course": "خرید؛ دو",
    "courses": "خرید",
    "cousin": "پسرخاله",
    "cousine": "دخترخاله",
    "coûte": "قیمت دارد",
    "couteau": "چاقو",
    "covoiturage": "سفر اشتراکی",
    "créative": "خلاق",
    "créatives": "خلاق",
    "créé": "ساخته",
    "crème": "کرم",
    "crêpes": "کرپ",
    "croissant": "کروسان",
    "croque": "گاز می‌زند",
    "cuillère": "قاشق",
    "cuir": "چرم",
    "cuisine": "آشپزخانه",
    "cuisinier": "آشپز",
    "cuisinons": "آشپزی می‌کنیم",
    "cuite": "پخته",
    "cv": "رزومه",
    "cyclable": "دوچرخه‌رو",
    "cyclisme": "دوچرخه‌سواری",
    "d'": "از",
    "dangereux": "خطرناک",
    "dans": "در",
    "danse": "رقص",
    "danser": "رقصیدن",
    "danseur": "رقصنده",
    "date": "تاریخ",
    "de": "از",
    "débutant": "مبتدی",
    "décembre": "دسامبر",
    "défaut": "نقص",
    "défendent": "دفاع می‌کنند",
    "défilé": "رژه",
    "dégustation": "چشیدن",
    "déjà": "از قبل",
    "déjeuner": "ناهار",
    "déjeunons": "ناهار می‌خوریم",
    "délégué": "نماینده",
    "delf": "آزمون دلف",
    "délicieuse": "خوشمزه",
    "délicieux": "خوشمزه",
    "demain": "فردا",
    "demande": "درخواست می‌کند",
    "déménagement": "اسباب‌کشی",
    "déménager": "اسباب‌کشی کردن",
    "demie": "و نیم",
    "dénoyaute": "هسته را درمی‌آورد",
    "dentifrice": "خمیر دندان",
    "dentiste": "دندان‌پزشک",
    "dents": "دندان‌ها",
    "déodorant": "دئودورانت",
    "départ": "حرکت",
    "départs": "پروازهای خروجی",
    "dépose": "تحویل می‌دهد",
    "depuis": "از",
    "dernier": "آخر",
    "des": "چند",
    "descend": "پیاده می‌شود",
    "désinfectant": "ضدعفونی",
    "désolé": "متأسفم",
    "dessert": "دسر",
    "desserts": "دسرها",
    "desservi": "خدمات‌رسانی می‌شود",
    "dessin": "نقاشی",
    "destination": "مقصد",
    "détends": "آرام می‌شوم",
    "déteste": "متنفر است",
    "deux": "دو",
    "devant": "جلوی",
    "dimanche": "یکشنبه",
    "dîner": "شام",
    "dînons": "شام می‌خوریم",
    "diplôme": "مدرک",
    "diplômé": "فارغ‌التحصیل",
    "diplômes": "مدارک",
    "dire": "گفتن",
    "directeur": "مدیر",
    "dispo": "آزاد",
    "disponible": "در دسترس",
    "dispose": "در اختیار دارد",
    "distance": "از راه دور",
    "distribuons": "پخش می‌کنیم",
    "distributeur": "دستگاه",
    "divorcé": "مطلق",
    "divorcée": "مطلقه",
    "dix": "ده",
    "dix-huit": "هجده",
    "dix-neuf": "نوزده",
    "dix-sept": "هفده",
    "dj": "دی‌جی",
    "docteur": "دکتر",
    "document": "مدرک",
    "documents": "مدارک",
    "doigt": "انگشت",
    "dois": "باید",
    "doit": "باید",
    "domicile": "منزل",
    "don": "کمک مالی",
    "donne": "می‌دهد",
    "donne-moi": "به من بده",
    "dons": "کمک‌ها",
    "dormir": "خوابیدن",
    "dors": "می‌خوابم",
    "dort": "می‌خوابد",
    "dos": "پشت",
    "dossier": "پرونده",
    "douane": "گمرک",
    "double": "دونفره",
    "douce": "ملایم",
    "doucement": "آرام",
    "douche": "دوش",
    "douleur": "درد",
    "douze": "دوازده",
    "droite": "راست",
    "drôle": "بامزه",
    "du": "از",
    "dur": "سفت",
    "dure": "طول می‌کشد",
    "dynamique": "پرانرژی",
    "e": "مؤنث",
    "e-mail": "ایمیل",
    "eau": "آب",
    "échanger": "عوض کردن",
    "écharpe": "شال",
    "école": "مدرسه",
    "économie": "اقتصاد",
    "économiser": "پس‌انداز کردن",
    "écouter": "گوش دادن",
    "écoutons": "گوش می‌دهیم",
    "écris": "می‌نویسم",
    "écrit": "می‌نویسد؛ کتبی",
    "écrivain": "نویسنده",
    "efficace": "مؤثر",
    "église": "کلیسا",
    "électricien": "برق‌کار",
    "électricité": "برق",
    "électrique": "برقی",
    "électronique": "الکترونیکی",
    "élégant": "شیک",
    "élève": "دانش‌آموز",
    "élèves": "دانش‌آموزان",
    "elle": "او",
    "embarquement": "سوار شدن",
    "embauche": "استخدام",
    "embouteillage": "ترافیک",
    "émission": "برنامه",
    "emménager": "اثاث‌کشی کردن به خانه",
    "émojis": "شکلک‌ها",
    "emploi": "شغل",
    "employé": "کارمند",
    "employés": "کارمندان",
    "employeur": "کارفرما",
    "emporter": "بیرون‌بر",
    "en": "در",
    "encore": "هنوز",
    "endors": "خوابم می‌برد",
    "endroit": "جا",
    "enfant": "بچه",
    "enfants": "بچه‌ها",
    "engagé": "متعهد",
    "engagement": "تعهد",
    "enrhumé": "سرماخورده",
    "enseignant": "معلم",
    "ensemble": "با هم",
    "entièrement": "کاملاً",
    "entraîne": "تمرین می‌دهد",
    "entraîneur": "مربی",
    "entre": "بین",
    "entrée": "پیش‌غذا؛ ورودی",
    "entrent": "وارد می‌شوند",
    "entreprise": "شرکت",
    "entretien": "مصاحبه",
    "environnement": "محیط زیست",
    "envoie": "می‌فرستد",
    "envoyer": "فرستادن",
    "épargne": "پس‌انداز",
    "épisode": "قسمت",
    "équilibré": "متعادل",
    "équipe": "تیم",
    "équipée": "مجهز",
    "es": "هستی",
    "escalier": "پله",
    "espace": "فضا",
    "espagnol": "اسپانیایی",
    "esprit": "روحیه",
    "essence": "بنزین",
    "essentielle": "ضروری",
    "est": "است",
    "et": "و",
    "étage": "طبقه",
    "était": "بود",
    "état": "وضعیت",
    "été": "تابستان؛ بوده",
    "éteint": "خاموش می‌کند",
    "être": "بودن",
    "étudiant": "دانشجو",
    "étudiants": "دانشجوها",
    "étudie": "درس می‌خواند",
    "étudié": "درس خوانده",
    "eu": "داشته",
    "euros": "یورو",
    "examen": "امتحان",
    "examine": "معاینه می‌کند",
    "excellent": "عالی",
    "excursion": "گردش",
    "excuse": "ببخشید",
    "expérience": "تجربه",
    "expiré": "منقضی",
    "explique": "توضیح می‌دهد",
    "exposé": "رو به",
    "expositions": "نمایشگاه‌ها",
    "face": "روبه‌رو",
    "facebook": "فیسبوک",
    "facile": "آسان",
    "façon": "طور",
    "facture": "قبض",
    "faculté": "دانشکده",
    "faire": "انجام دادن",
    "fais": "می‌کنم",
    "faisons": "می‌کنیم",
    "fait": "می‌کند",
    "famille": "خانواده",
    "farine": "آرد",
    "fast-food": "فست‌فود",
    "fatigué": "خسته",
    "fausses": "دروغین",
    "faut": "باید",
    "femme": "زن",
    "fenêtre": "پنجره",
    "fête": "جشن",
    "feu": "آتش؛ چراغ",
    "feuilles": "برگ‌ها",
    "février": "فوریه",
    "fiable": "معتبر",
    "fichier": "فایل",
    "fille": "دختر",
    "film": "فیلم",
    "films": "فیلم‌ها",
    "fils": "پسر",
    "fin": "پایان",
    "finir": "تمام کردن",
    "finit": "تمام می‌شود",
    "fiscal": "مالیاتی",
    "fitness": "بدنسازی",
    "fixé": "تعیین شده",
    "fleur": "گل",
    "fois": "بار",
    "fonctionne": "کار می‌کند",
    "fondre": "آب کردن",
    "foot": "فوتبال",
    "football": "فوتبال",
    "forêt": "جنگل",
    "forfait": "بسته",
    "formation": "دوره",
    "forte": "شدید",
    "fortes": "شدید",
    "forum": "انجمن",
    "four": "فر",
    "fourchette": "چنگال",
    "fraîche": "تازه؛ خنک",
    "frais": "تازه",
    "fraise": "توت‌فرنگی",
    "fraises": "توت‌فرنگی",
    "français": "فرانسوی",
    "française": "فرانسوی",
    "france": "فرانسه",
    "frère": "برادر",
    "frigo": "یخچال",
    "frites": "سیب‌زمینی سرخ‌کرده",
    "froid": "سرد",
    "fromage": "پنیر",
    "fruits": "میوه‌ها",
    "fuite": "نشتی",
    "fume": "سیگار می‌کشد",
    "fumer": "سیگار کشیدن",
    "gagné": "برنده شده",
    "gants": "دستکش",
    "garage": "گاراژ",
    "garagiste": "مکانیک",
    "garantie": "گارانتی",
    "garçon": "پسر",
    "gardienne": "سرایدار",
    "gare": "ایستگاه قطار",
    "gastronomie": "غذا",
    "gâteau": "کیک",
    "gâteaux": "شیرینی",
    "gauche": "چپ",
    "gaz": "گاز",
    "gazeuse": "گازدار",
    "gel": "ژل",
    "général": "کلی",
    "gentil": "مهربان",
    "gentille": "مهربان",
    "glace": "بستنی",
    "gorge": "گلو",
    "goûter": "عصرانه",
    "gps": "جی‌پی‌اس",
    "grammes": "گرم",
    "grand": "بزرگ",
    "grand-père": "پدربزرگ",
    "grande": "بزرگ",
    "grands-parents": "پدربزرگ و مادربزرگ",
    "gratuit": "رایگان",
    "gratuite": "رایگان",
    "gratuits": "رایگان",
    "grève": "اعتصاب",
    "grippe": "آنفولانزا",
    "gris": "خاکستری",
    "grise": "خاکستری",
    "grossis": "چاق می‌شوم",
    "groupe": "گروه",
    "guérit": "درمان می‌کند",
    "guichet": "گیشه",
    "guide": "راهنما",
    "guidée": "راهنمایی‌شده",
    "guitare": "گیتار",
    "gym": "ورزش",
    "gymnase": "سالن ورزش",
    "habille": "لباس می‌پوشد",
    "habitants": "ساکنان",
    "habite": "زندگی می‌کند",
    "habitent": "زندگی می‌کنند",
    "hall": "سالن ورودی",
    "hâte": "بی‌صبری",
    "herbe": "چمن",
    "heure": "ساعت",
    "heures": "ساعت",
    "heureuse": "خوشحال",
    "hier": "دیروز",
    "histoire": "تاریخ",
    "hiver": "زمستان",
    "homme": "مرد",
    "hommes": "مردها",
    "hôpital": "بیمارستان",
    "hôtel": "هتل",
    "hôtesse": "مهماندار",
    "hugo": "هوگو",
    "huit": "هشت",
    "humaines": "انسانی",
    "ici": "اینجا",
    "identité": "هویت",
    "il": "او",
    "illimités": "نامحدود",
    "ils": "آن‌ها",
    "immatriculation": "پلاک",
    "immeuble": "ساختمان",
    "immobilière": "املاک",
    "important": "مهم",
    "importante": "مهم",
    "importants": "مهم",
    "inclus": "شامل",
    "incontournable": "نباید از دست داد",
    "incroyable": "باورنکردنی",
    "infirmier": "پرستار",
    "infirmière": "پرستار",
    "informaticien": "متخصص کامپیوتر",
    "information": "اطلاعات",
    "informations": "اطلاعات",
    "informatique": "کامپیوتر",
    "infos": "خبرها",
    "ingénieur": "مهندس",
    "ingrédient": "مواد لازم",
    "inscrire": "ثبت‌نام کردن",
    "insomnie": "بی‌خوابی",
    "instagram": "اینستاگرام",
    "installe": "نصب می‌کند",
    "insupportable": "غیرقابل تحمل",
    "intègre": "وارد می‌شود",
    "interdit": "ممنوع",
    "intéressant": "جالب",
    "intéressante": "جالب",
    "intérêt": "علاقه",
    "intérieur": "داخلی",
    "intermédiaire": "متوسط",
    "internet": "اینترنت",
    "interrompu": "قطع شده",
    "investit": "وقت می‌گذارد",
    "invitation": "دعوت",
    "invités": "مهمان‌ها",
    "italie": "ایتالیا",
    "italien": "ایتالیایی",
    "italienne": "ایتالیایی",
    "itinéraire": "مسیر",
    "j'": "من",
    "jambe": "پا",
    "janvier": "ژانویه",
    "jardin": "باغ",
    "jaune": "زرد",
    "je": "من",
    "jean": "شلوار جین",
    "jeu": "بازی",
    "jeudi": "پنجشنبه",
    "jeune": "جوان",
    "jeunes": "جوان‌ها",
    "joli": "قشنگ",
    "jolie": "قشنگ",
    "joue": "بازی می‌کند",
    "jouent": "بازی می‌کنند",
    "jouer": "بازی کردن",
    "joueur": "بازیکن",
    "joueurs": "بازیکنان",
    "jouons": "بازی می‌کنیم",
    "jour": "روز",
    "journal": "روزنامه",
    "journaliste": "خبرنگار",
    "journée": "روز",
    "jours": "روزها",
    "jt": "اخبار تلویزیون",
    "juillet": "ژوئیه",
    "juin": "ژوئن",
    "julie": "ژولی",
    "jupe": "دامن",
    "jus": "آبمیوه",
    "justificatif": "مدرک",
    "kermesse": "جشن مدرسه",
    "kiwi": "کیوی",
    "l": "سایز لارج",
    "l'": "the",
    "l'après-midi": "بعدازظهر",
    "la": "the، مؤنث",
    "laine": "پشم",
    "laisse": "می‌گذارد؛ قلاده",
    "laisser": "گذاشتن",
    "lait": "شیر",
    "laitiers": "لبنیات",
    "lampe": "چراغ",
    "langues": "زبان‌ها",
    "large": "پهن",
    "lave": "می‌شوید",
    "le": "the، مذکر",
    "léger": "سبک",
    "lente": "کند",
    "lentement": "آهسته",
    "les": "the، جمع",
    "lettre": "نامه",
    "lettres": "ادبیات؛ نامه‌ها",
    "leurs": "مال آن‌ها",
    "lève": "بلند می‌شود",
    "lèvres": "لب‌ها",
    "liaison": "ارتباط",
    "libre": "آزاد",
    "licence": "لیسانس",
    "lieu": "مکان",
    "lieux": "محل",
    "ligne": "خط؛ آنلاین",
    "lilicool": "نام کاربری",
    "lire": "خواندن",
    "lis": "می‌خوانم",
    "liste": "فهرست",
    "lit": "می‌خواند؛ تخت",
    "livraison": "تحویل",
    "livre": "کتاب",
    "livres": "کتاب‌ها",
    "livret": "دفترچه حساب",
    "livreur": "پیک",
    "local": "محلی",
    "localisation": "موقعیت مکانی",
    "locataire": "مستأجر",
    "location": "اجاره",
    "logement": "مسکن",
    "loin": "دور",
    "loisirs": "اوقات فراغت",
    "long": "طولانی",
    "loue": "اجاره می‌کند",
    "louer": "اجاره کردن",
    "lourd": "سنگین",
    "loyer": "اجاره",
    "lu": "خوانده",
    "lumière": "نور",
    "lumineux": "روشن",
    "lundi": "دوشنبه",
    "lunettes": "عینک",
    "lycée": "دبیرستان",
    "lyon": "لیون",
    "m": "سایز مدیوم",
    "m'": "خودم",
    "ma": "مال من",
    "machine": "دستگاه",
    "magasin": "فروشگاه",
    "magistral": "درس نظری",
    "magnifique": "فوق‌العاده",
    "mai": "مه",
    "maigrit": "لاغر می‌شود",
    "main": "دست",
    "mais": "اما",
    "maison": "خانه",
    "mal": "درد؛ بد",
    "malade": "بیمار",
    "malheureusement": "متأسفانه",
    "mange": "می‌خورد",
    "mangeons": "می‌خوریم",
    "manteau": "پالتو",
    "maquillage": "آرایش",
    "maquille": "آرایش می‌کند",
    "marche": "کار می‌کند؛ پیاده‌روی",
    "marché": "بازار",
    "marchons": "پیاده می‌رویم",
    "mardi": "سه‌شنبه",
    "mari": "شوهر",
    "mariage": "ازدواج",
    "marie": "ماری",
    "marié": "متأهل",
    "mariée": "متأهل",
    "marier": "ازدواج کردن",
    "marque": "گل می‌زند؛ برند",
    "marron": "قهوه‌ای",
    "mars": "مارس",
    "massage": "ماساژ",
    "master": "فوق‌لیسانس",
    "match": "مسابقه",
    "maternelle": "پیش‌دبستانی",
    "mathématiques": "ریاضی",
    "maths": "ریاضی",
    "matin": "صبح",
    "matins": "صبح‌ها",
    "mauvais": "بد",
    "mauvaise": "بد",
    "me": "خودم",
    "médecin": "پزشک",
    "médias": "رسانه‌ها",
    "médical": "پزشکی",
    "médicament": "دارو",
    "mélange": "مخلوط می‌کند",
    "membre": "عضو",
    "même": "همان",
    "menu": "منو",
    "mer": "دریا",
    "mercredi": "چهارشنبه",
    "mère": "مادر",
    "mes": "مال من",
    "mesure": "اندازه",
    "met": "می‌گذارد",
    "métier": "شغل",
    "métro": "مترو",
    "mets": "می‌گذارم",
    "mettre": "گذاشتن",
    "meublé": "مبله",
    "meubles": "اثاث",
    "midi": "ظهر",
    "militaire": "نظامی",
    "millilitres": "میلی‌لیتر",
    "minuit": "نیمه‌شب",
    "minutes": "دقیقه",
    "miroir": "آینه",
    "mission": "مأموریت",
    "mobile": "موبایل",
    "mobilisent": "بسیج می‌کنند",
    "mode": "حالت",
    "moderne": "مدرن",
    "modes": "شیوه‌ها",
    "moi": "من",
    "moins": "کمتر",
    "mois": "ماه",
    "mon": "مال من",
    "monde": "دنیا",
    "montagne": "کوه",
    "monte": "بالا می‌رود",
    "monter": "سوار شدن",
    "montre": "نشان می‌دهد",
    "morceau": "تکه",
    "mot": "کلمه",
    "motivation": "انگیزه‌نامه",
    "motivé": "باانگیزه",
    "motivée": "باانگیزه",
    "moule": "قالب",
    "municipale": "شهرداری",
    "musculation": "بدنسازی",
    "musée": "موزه",
    "musicien": "نوازنده",
    "musique": "موسیقی",
    "n'": "نه",
    "nage": "شنا می‌کند",
    "nager": "شنا کردن",
    "natation": "شنا",
    "nationale": "ملی",
    "nature": "طبیعت",
    "navette": "اتوبوس رفت‌وبرگشت",
    "ne": "نه",
    "négocie": "چانه می‌زند",
    "neige": "برف",
    "net": "خالص",
    "nettoie": "تمیز می‌کند",
    "nettoyer": "تمیز کردن",
    "neuf": "نُه؛ نو",
    "neuve": "نو",
    "nez": "بینی",
    "noces": "عروسی",
    "noël": "کریسمس",
    "noir": "مشکی",
    "noire": "مشکی",
    "nom": "نام خانوادگی",
    "nos": "مال ما",
    "note": "نمره",
    "notes": "نمره‌ها",
    "notice": "بروشور",
    "notre": "مال ما",
    "nourriture": "غذا",
    "nous": "ما",
    "nouvel": "جدید",
    "nouvelle": "جدید",
    "novembre": "نوامبر",
    "nuit": "شب",
    "numéro": "شماره",
    "obligatoire": "اجباری",
    "occasion": "دست‌دوم",
    "octobre": "اکتبر",
    "œuf": "تخم‌مرغ",
    "œufs": "تخم‌مرغ",
    "office": "دفتر",
    "offre": "پیشنهاد",
    "offrir": "هدیه دادن",
    "oignon": "پیاز",
    "omelette": "املت",
    "on": "آدم",
    "oncle": "عمو",
    "onglet": "زبانه",
    "ont": "دارند",
    "onze": "یازده",
    "opérateur": "اپراتور",
    "opéré": "جراحی شده",
    "oral": "شفاهی",
    "orange": "پرتقال؛ نارنجی",
    "ordinateur": "کامپیوتر",
    "ordonnance": "نسخه",
    "oreille": "گوش",
    "organise": "برگزار می‌کند",
    "organisé": "منظم",
    "organisée": "برگزار شده",
    "ou": "یا",
    "où": "کجا",
    "oublie": "فراموش می‌کند",
    "ouvre": "باز می‌کند",
    "ouvrir": "باز کردن",
    "pacsé": "هم‌خانگی رسمی",
    "pacsée": "هم‌خانگی رسمی",
    "paie": "پرداخت می‌کند",
    "paiement": "پرداخت",
    "pain": "نان",
    "panne": "خرابی",
    "pansement": "چسب زخم",
    "pantalon": "شلوار",
    "papier": "کاغذ",
    "papiers": "کاغذها",
    "par": "با؛ از طریق",
    "parc": "پارک",
    "parents": "والدین",
    "parents-profs": "جلسهٔ اولیا و مربیان",
    "parfait": "عالی",
    "parfum": "عطر",
    "paris": "پاریس",
    "parking": "پارکینگ",
    "parle": "حرف می‌زند",
    "parlons": "حرف می‌زنیم",
    "part": "راه می‌افتد؛ سهم",
    "partageons": "به اشتراک می‌گذاریم",
    "partager": "به اشتراک گذاشتن",
    "partent": "راه می‌افتند",
    "participant": "شرکت‌کننده",
    "participe": "شرکت می‌کند",
    "participer": "شرکت کردن",
    "participons": "شرکت می‌کنیم",
    "particuliers": "افراد حقیقی",
    "partie": "بازی",
    "partir": "راه افتادن",
    "partons": "راه می‌افتیم",
    "pas": "نه",
    "passage": "گذرگاه",
    "passager": "مسافر",
    "passe": "رد می‌شود؛ می‌گذراند",
    "passé": "گذشته",
    "passent": "رد می‌شوند",
    "passeport": "گذرنامه",
    "passeports": "گذرنامه‌ها",
    "passion": "علاقه",
    "passons": "می‌گذریم",
    "pastille": "قرص مکیدنی",
    "pâte": "خمیر",
    "pâtes": "پاستا",
    "patient": "بیمار؛ صبور",
    "patiente": "صبور",
    "paul": "پل",
    "pause": "استراحت",
    "pauvres": "فقرا",
    "payer": "پرداخت کردن",
    "payés": "باحقوق",
    "paysages": "منظره‌ها",
    "pédagogique": "آموزشی",
    "peindre": "نقاشی کردن",
    "peintre": "نقاش",
    "peinture": "نقاشی",
    "pendant": "در طول",
    "perdu": "گم‌شده",
    "père": "پدر",
    "permis": "گواهینامه",
    "personnage": "شخصیت",
    "personnel": "شخصی",
    "personnes": "افراد",
    "petit": "کوچک",
    "petit-déjeuner": "صبحانه",
    "petite": "کوچک",
    "petits-enfants": "نوه‌ها",
    "peu": "کم",
    "peut": "می‌تواند",
    "pharmacie": "داروخانه",
    "pharmacien": "داروساز",
    "photo": "عکس",
    "picasso": "پیکاسو",
    "pièce": "اتاق؛ مدرک",
    "pièces": "اتاق",
    "pied": "پا",
    "pierre": "پیر",
    "piéton": "عابر پیاده",
    "piétons": "عابران",
    "pinceau": "قلم‌مو",
    "piqûre": "آمپول",
    "piscine": "استخر",
    "piste": "مسیر",
    "pizza": "پیتزا",
    "place": "جا؛ میدان",
    "plage": "ساحل",
    "plaie": "زخم",
    "plaît": "خوش می‌آید",
    "plaque": "پلاک",
    "plat": "غذا",
    "plate": "بدون گاز",
    "plateforme": "سکو",
    "plein": "پر",
    "pleine": "پر",
    "pleut": "باران می‌بارد",
    "plombier": "لوله‌کش",
    "pluie": "باران",
    "plus": "بیشتر",
    "pneumonie": "ذات‌الریه",
    "podcast": "پادکست",
    "poêle": "ماهی‌تابه",
    "poids": "وزن",
    "poisson": "ماهی",
    "poivron": "فلفل دلمه‌ای",
    "pollution": "آلودگی",
    "pomme": "سیب",
    "pommes": "سیب",
    "portable": "موبایل",
    "porte": "می‌پوشد؛ در",
    "pose": "می‌پرسد",
    "poser": "پرسیدن",
    "postal": "پستی",
    "poste": "پست",
    "postule": "درخواست می‌دهد",
    "poubelle": "سطل زباله",
    "poubelles": "سطل زباله",
    "poulet": "مرغ",
    "poumons": "ریه‌ها",
    "pour": "برای",
    "pourboire": "انعام",
    "précieuse": "ارزشمند",
    "préfecture": "فرمانداری",
    "préfère": "ترجیح می‌دهد",
    "prend": "برمی‌دارد",
    "prendre": "گرفتن",
    "prends": "برمی‌دارم",
    "prennent": "برمی‌دارند",
    "prénom": "اسم کوچک",
    "prenons": "برمی‌داریم",
    "préparation": "آماده‌سازی",
    "prépare": "آماده می‌کند",
    "préparé": "آماده شده",
    "près": "نزدیک",
    "présentation": "ارائه",
    "présentatrice": "مجری",
    "présente": "معرفی می‌کند",
    "presse": "مطبوعات",
    "primaire": "دبستان",
    "principal": "اصلی",
    "printemps": "بهار",
    "pris": "گرفته",
    "prise": "گرفتن",
    "prix": "قیمت",
    "problème": "مشکل",
    "prochain": "بعدی",
    "proche": "نزدیک",
    "produits": "محصولات",
    "prof": "استاد",
    "professeur": "معلم",
    "professionnel": "حرفه‌ای",
    "professionnelle": "حرفه‌ای",
    "profil": "پروفایل",
    "profitons": "استفاده می‌کنیم",
    "programme": "برنامه",
    "projet": "پروژه",
    "promenons": "قدم می‌زنیم",
    "propose": "پیشنهاد می‌کند",
    "propre": "تمیز",
    "propriétaire": "مالک",
    "prudent": "محتاط",
    "pseudo": "نام مستعار",
    "publics": "عمومی",
    "puis-je": "می‌توانم",
    "pull": "پلیور",
    "quai": "سکو",
    "qualité": "کیفیت",
    "qualité-prix": "کیفیت نسبت به قیمت",
    "quand": "کی",
    "quarante": "چهل",
    "quart": "ربع",
    "quartier": "محله",
    "quatorze": "چهارده",
    "quatre": "چهار",
    "quatre-vingt-dix": "نود",
    "quatre-vingts": "هشتاد",
    "que": "که",
    "quel": "کدام",
    "quelle": "کدام",
    "question": "سؤال",
    "questions": "سؤال‌ها",
    "quiche": "کیش",
    "quinze": "پانزده",
    "radio": "رادیو",
    "raisin": "انگور",
    "randonnée": "کوه‌پیمایی",
    "range": "مرتب می‌کند",
    "rapide": "سریع",
    "rapidement": "سریع",
    "rapides": "سریع",
    "rapport": "نسبت",
    "rase": "اصلاح می‌کند",
    "raté": "مردود شده",
    "ravi": "خوشحال",
    "récépissé": "رسید",
    "réception": "پذیرش",
    "rechercher": "جستجو کردن",
    "recherches": "تحقیق",
    "reçoit": "پذیرا می‌شود",
    "récoltent": "جمع می‌کنند",
    "recommandée": "سفارشی",
    "récréation": "زنگ تفریح",
    "recruté": "استخدام شده",
    "recruteur": "استخدام‌کننده",
    "reçu": "دریافت کرده",
    "récupérer": "پس گرفتن",
    "rédige": "می‌نویسد",
    "réfugiés": "پناهندگان",
    "refuser": "رد کردن",
    "regarde": "نگاه می‌کند",
    "regardé": "تماشا کرده",
    "regarder": "تماشا کردن",
    "régime": "رژیم",
    "règle": "قانون",
    "règlement": "مقررات",
    "régulière": "قانونی",
    "relais": "ایستگاه بین‌راهی",
    "remercier": "تشکر کردن",
    "remplacement": "جایگزینی",
    "remplis": "پر می‌کنم",
    "rencontre": "ملاقات",
    "rendez-vous": "قرار",
    "rendre": "پس دادن",
    "rendu": "تحویل داده",
    "renouveler": "تمدید کردن",
    "rénové": "بازسازی‌شده",
    "rentrée": "شروع مدارس",
    "réparation": "تعمیر",
    "répare": "تعمیر می‌کند",
    "réparer": "تعمیر کردن",
    "repas": "غذا",
    "répondre": "جواب دادن",
    "repose": "استراحت می‌کند",
    "réservé": "رزرو شده",
    "réserver": "رزرو کردن",
    "résilié": "لغو شده",
    "respecter": "رعایت کردن",
    "responsable": "مسئول",
    "ressources": "منابع",
    "restaurant": "رستوران",
    "restaurateur": "رستوران‌دار",
    "reste": "می‌ماند",
    "rester": "ماندن",
    "résultats": "نتایج",
    "retard": "تأخیر",
    "retire": "برمی‌دارد",
    "retirer": "تحویل گرفتن",
    "rétroviseur": "آینه",
    "réunion": "جلسه",
    "réussi": "قبول شده",
    "rêve": "خواب",
    "révisions": "مرور درس",
    "rhume": "سرماخوردگی",
    "rigolos": "بامزه",
    "riz": "برنج",
    "robe": "لباس",
    "roman": "رمان",
    "rose": "صورتی؛ گل رز",
    "rouge": "قرمز",
    "roule": "رانندگی می‌کند",
    "rousse": "موقرمز",
    "route": "جاده",
    "roux": "موقرمز",
    "rue": "خیابان",
    "russe": "روسی",
    "s'": "خودش",
    "sa": "مال او",
    "sac": "کیف",
    "sachet": "پاکت",
    "saison": "فصل",
    "saisons": "فصل‌ها",
    "sait": "می‌داند",
    "salade": "سالاد",
    "salaire": "حقوق",
    "sale": "کثیف",
    "salle": "سالن",
    "salon": "اتاق نشیمن",
    "salsa": "سالسا",
    "samedi": "شنبه",
    "sandwich": "ساندویچ",
    "sang": "خون",
    "sans": "بدون",
    "santé": "سلامت",
    "saumon": "سالمون",
    "sauvegarde": "ذخیره می‌کند",
    "savon": "صابون",
    "sciences": "علوم",
    "scolaire": "مدرسه",
    "scolarité": "تحصیل",
    "se": "خودش",
    "séance": "سانس",
    "sèche": "خشک",
    "secrétariat": "دفتر دبیرخانه",
    "secteur": "بخش",
    "sécurité": "امنیت",
    "seize": "شانزده",
    "séjour": "اقامت",
    "sel": "نمک",
    "semaine": "هفته",
    "sens": "معنی",
    "séparé": "جدا",
    "séparée": "جدا",
    "séparés": "جدا",
    "sept": "هفت",
    "septembre": "سپتامبر",
    "série": "سریال",
    "sérieux": "جدی",
    "serrent": "می‌فشارند",
    "serrure": "قفل",
    "serrurier": "قفل‌ساز",
    "serveur": "گارسون",
    "service": "خدمات",
    "services": "خدمات",
    "serviettes": "دستمال",
    "ses": "مال او",
    "shampoing": "شامپو",
    "short": "شلوارک",
    "sieste": "چرت",
    "signaler": "اعلام کردن",
    "signe": "امضا می‌کند",
    "signé": "امضا کرد",
    "signer": "امضا کردن",
    "simple": "یک‌نفره",
    "sirop": "شربت",
    "site": "سایت",
    "situation": "وضعیت",
    "situations": "موقعیت‌ها",
    "six": "شش",
    "ski": "اسکی",
    "sms": "پیامک",
    "social": "اجتماعی",
    "sociaux": "اجتماعی",
    "société": "شرکت",
    "soda": "نوشابه",
    "sœur": "خواهر",
    "soigne": "درمان می‌کند",
    "soir": "عصر",
    "soirée": "شب‌نشینی",
    "soirs": "عصرها",
    "soixante": "شصت",
    "soixante-dix": "هفتاد",
    "solaire": "آفتابی",
    "soldes": "حراج",
    "soleil": "خورشید",
    "solidaires": "همبسته",
    "solidarité": "همبستگی",
    "sommes": "هستیم",
    "son": "مال او",
    "sont": "هستند",
    "sophie": "سوفی",
    "sort": "بیرون می‌رود",
    "sortie": "خروجی",
    "sortir": "بیرون رفتن",
    "soupe": "سوپ",
    "souriant": "خندان",
    "souris": "موشواره",
    "sous": "زیر",
    "sous-titres": "زیرنویس",
    "soutien": "حمایت",
    "souvent": "اغلب",
    "spécialiste": "متخصص",
    "spécialité": "غذای مخصوص",
    "spectacle": "نمایش",
    "sport": "ورزش",
    "sportive": "ورزشی",
    "stade": "ورزشگاه",
    "stage": "کارآموزی",
    "stagiaire": "کارآموز",
    "stand": "غرفه",
    "station": "ایستگاه",
    "station-service": "پمپ بنزین",
    "stationner": "پارک کردن",
    "steak": "استیک",
    "stressée": "مضطرب",
    "strict": "سخت‌گیر",
    "studio": "سوئیت یک‌خوابه",
    "suce": "می‌مکد",
    "sucre": "شکر",
    "sucré": "شیرین",
    "sud": "جنوب",
    "suis": "هستم",
    "suisse": "سوئیسی",
    "suite": "ادامه",
    "suivante": "بعدی",
    "super": "عالی",
    "supermarché": "سوپرمارکت",
    "supplément": "اضافه",
    "sur": "روی",
    "sûreté": "امنیت",
    "surf": "موج‌سواری",
    "sympa": "دوست‌داشتنی",
    "sympathique": "مهربان",
    "sympathiques": "مهربان",
    "t-shirt": "تی‌شرت",
    "t'": "تو را",
    "t2": "آپارتمان دو اتاقه",
    "table": "میز",
    "tableau": "تابلو",
    "taille": "سایز",
    "tante": "خاله",
    "tarte": "تارت",
    "te": "تو را",
    "technicien": "تکنسین",
    "technicienne": "تکنسین",
    "technique": "فنی",
    "télé": "تلویزیون",
    "téléphone": "تلفن",
    "télétravail": "دورکاری",
    "télévision": "تلویزیون",
    "température": "دما",
    "temps": "زمان؛ هوا",
    "tennis": "تنیس",
    "terminal": "ترمینال",
    "terrasse": "تراس",
    "tête": "سر",
    "thé": "چای",
    "théâtre": "تئاتر",
    "ticket": "بلیت",
    "tiens": "نگه می‌دارم",
    "timbre": "تمبر",
    "titre": "عنوان",
    "toi": "تو",
    "toilette": "دستشویی",
    "toilettes": "دستشویی",
    "tomate": "گوجه‌فرنگی",
    "tombent": "می‌ریزند",
    "tombola": "قرعه‌کشی",
    "ton": "مال تو",
    "toujours": "همیشه",
    "tourisme": "گردشگری",
    "tourne": "برمی‌گرداند",
    "tournez": "بپیچید",
    "tous": "همه",
    "tousse": "سرفه می‌کند",
    "tout": "همه",
    "toute": "تمام",
    "toutes": "همه",
    "toux": "سرفه",
    "trafic": "ترافیک",
    "train": "قطار",
    "traitement": "درمان",
    "traiteur": "تهیه‌کنندهٔ غذا",
    "trajet": "مسیر",
    "tramway": "تراموا",
    "tranche": "برش",
    "tranquille": "آرام",
    "transférer": "انتقال دادن",
    "transport": "حمل‌ونقل",
    "transporte": "حمل می‌کند",
    "transports": "حمل‌ونقل",
    "travail": "کار",
    "travaille": "کار می‌کند",
    "travaillent": "کار می‌کنند",
    "travaux": "کارهای عمرانی",
    "traversez": "عبور کنید",
    "traversons": "رد می‌شویم",
    "treize": "سیزده",
    "trente": "سی",
    "très": "خیلی",
    "tricher": "تقلب کردن",
    "trimestre": "سه‌ماهه",
    "trois": "سه",
    "troisième": "سوم",
    "trop": "خیلی زیاد",
    "trottoir": "پیاده‌رو",
    "trouve": "پیدا می‌کند",
    "trouvé": "پیدا کرده",
    "trouver": "پیدا کردن",
    "tu": "تو",
    "type": "نوع",
    "typique": "معمول",
    "un": "یک",
    "une": "یک",
    "universitaire": "دانشگاهی",
    "université": "دانشگاه",
    "urgences": "اورژانس",
    "urgente": "فوری",
    "usb": "فلش",
    "utile": "مفید",
    "utilise": "استفاده می‌کند",
    "utilisent": "استفاده می‌کنند",
    "utilisons": "استفاده می‌کنیم",
    "va": "می‌رود",
    "vacances": "تعطیلات",
    "vaccinés": "واکسینه",
    "vagues": "موج‌ها",
    "vais": "می‌روم",
    "vaisselle": "ظرف‌ها",
    "valable": "معتبر",
    "valide": "معتبر",
    "validité": "اعتبار",
    "valise": "چمدان",
    "variée": "گوناگون",
    "véhicule": "وسیله",
    "vélo": "دوچرخه",
    "vélos": "دوچرخه‌ها",
    "vendeur": "فروشنده",
    "vendredi": "جمعه",
    "venir": "آمدن",
    "ventre": "شکم",
    "verdure": "سبزه",
    "vérifie": "بررسی می‌کند",
    "vérifier": "بررسی کردن",
    "verre": "لیوان",
    "verse": "می‌ریزد",
    "vert": "سبز",
    "verte": "سبز",
    "veste": "کت",
    "vêtements": "لباس‌ها",
    "veuf": "بیوه",
    "veut": "می‌خواهد",
    "veuve": "بیوه",
    "veux": "می‌خواهم",
    "viande": "گوشت",
    "victor": "ویکتور",
    "vidéo": "ویدیو",
    "vidéos": "ویدیوها",
    "vie": "زندگی",
    "vient": "می‌آید",
    "vieux": "قدیمی",
    "village": "روستا",
    "ville": "شهر",
    "vin": "شراب",
    "vingt": "بیست",
    "violette": "بنفش",
    "vis": "زندگی می‌کنم",
    "visa": "ویزا",
    "visage": "صورت",
    "visioconférence": "ویدیوکنفرانس",
    "visite": "بازدید",
    "visiter": "بازدید کردن",
    "visitons": "بازدید می‌کنیم",
    "vitale": "درمانی",
    "vite": "سریع",
    "vivent": "زندگی می‌کنند",
    "vivre": "زندگی کردن",
    "voici": "این است",
    "voir": "دیدن",
    "voisin": "همسایه",
    "voisine": "همسایه",
    "voisins": "همسایه‌ها",
    "voiture": "ماشین",
    "voitures": "ماشین‌ها",
    "voix": "صدا",
    "vol": "پرواز",
    "vomit": "استفراغ می‌کند",
    "vont": "می‌روند",
    "voudrais": "می‌خواهم",
    "vous": "شما",
    "voyage": "سفر",
    "voyager": "سفر کردن",
    "vu": "دیده",
    "vue": "چشم‌انداز",
    "wc": "دستشویی",
    "week-end": "آخر هفته",
    "wi-fi": "وای‌فای",
    "y": "آنجا",
    "yeux": "چشم‌ها",
    "yoga": "یوگا",
    "zéro": "صفر"
  },
  phrases: {
    "il faut": "باید",
    "il pleut": "باران می‌بارد",
    "il y": "آنجا",
    "y a": "وجود دارد",
    "s' il": "اگر",
    "te plaît": "لطفاً",
    "vous plaît": "لطفاً",
    "ce soir": "امشب",
    "la porte": "در",
    "une porte": "در",
    "le lit": "تخت",
    "un lit": "تخت",
    "tu cours": "تو می‌دوی",
    "en laisse": "با قلاده",
    "d' artifice": "آتش‌بازی",
    "le matin": "صبح",
    "le soir": "عصر",
    "en ligne": "آنلاین",
    "d' identité": "شناسایی",
    "de travail": "کاری",
    "au foot": "فوتبال",
    "l' après-midi": "بعدازظهر",
    "ai mal": "درد دارم",
    "mal à": "دردِ",
    "près de": "نزدیک",
    "un peu": "کمی",
    "beaucoup de": "مقدار زیادی",
    "pas de": "بدون",
    "en face": "روبه‌رو",
    "carte d'": "کارتِ",
    "sac à": "کیف",
    "à dos": "پشتی",
    "eau plate": "آب بدون گاز",
    "eau gazeuse": "آب گازدار",
    "petit déjeuner": "صبحانه",
    "rendez vous": "قرار",
    "week end": "آخر هفته",
    "centre ville": "مرکز شهر",
    "tout le": "تمام",
    "tous les": "هر",
    "de plus": "به‌علاوه",
    "parce que": "چون",
    "quel âge": "چند سال",
    "n' est": "نیست",
    "ne suis": "نیستم",
    "ne veux": "نمی‌خواهم",
    "ne peux": "نمی‌توانم",
    "ne sais": "نمی‌دانم",
    "j' ai": "من دارم",
    "je suis": "من هستم",
    "c' est": "این است",
    "il est": "او هست",
    "elle est": "او هست"
  }
};
